// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CustomCells13
{
    public partial class CustomTableViewCell : UITableViewCell
    {
        public static readonly NSString Key = new NSString(nameof(CustomTableViewCell));

        #region Properties

        public UIImage imageLike { get => imgProfile.Image; set => imgProfile.Image = value; }
        public string Label
        {
            get => lbl.Text;
            set => lbl.Text = value;
        }
        public string Like
        {
            
            get => lbl2.Text;
            set => lbl2.Text = value;
        }

        public NSIndexPath IndexPath
        {
            get;
            set;
        }
        #endregion

        public CustomTableViewCell(IntPtr handle) : base(handle)
        {
            
        }

        #region User Interaction


        #endregion

        #region Internal Functionality


        #endregion
    }
}
